markdown: rdiscount
pygments: true
permalink: /posts/:title
auto: true
rdiscount:
  extensions: [smart]

name: Jonathan Almeida
url: http://jonalmeida.github.com
description: A journal from the Nether and back again.
twitter: jonalmeida942
github: jonalmeida
gravatar_url: http://www.gravatar.com/avatar/58dc5af4d6bc1e0f6fd4c25dea7b2b8e.png