permalink: /posts/:title
markdown: kramdown

gems:
  - jekyll-sitemap
  - jekyll-archives

name: Jonathan Almeida 
url: https://jonalmeida.com
description: Thoughts and opinions.
twitter: jonalmeida_
github: jonalmeida
gravatar_url: https://www.gravatar.com/avatar/58dc5af4d6bc1e0f6fd4c25dea7b2b8e

jekyll-archives:
  enabled: all
  layout: archive
  permalinks:
    year: '/:year/'
    month: '/:year/:month/'
    day: '/:year/:month/:day/'
    tag: '/tag/:name/'
    category: '/category/:name/'