name: Build and deploy GH Pages

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    steps:
      - name: checkout
        uses: actions/checkout@v4
      - name: build_and_deploy
        uses: shalzz/zola-deploy-action@2f512f31e2e912d5fbd15f319c9c1bfbcfa90a55 # v0.23.4
        env:
          TOKEN: ${{ secrets.GITHUB_TOKEN }}
